spring:
  application:
    name: ws-user-management
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ws-user-management
    show-sql: false
  flyway:
    enabled: true
    schemas: ws-user-management
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration
    baseline-version: 1
server:
  port: 18762
  servlet:
    encoding:
      force: true
      charset: UTF-8
jwt:
  public:
    key: ${JWT_PUBLIC_SECRET_KEY}
  access-token:
    expiration: 3600000
  refresh-token:
    expiration: 36000000
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER}
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    prefer-ip-address: true